master <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors=FALSE)
master$Date <- as.Date(master$Date, format = "%d/%m/%Y")
data <- subset(master, master$Date >= '2007-02-01' & master$Date <= '2007-02-02')
data$Global_active_power <- as.numeric(data$Global_active_power, na.rm = TRUE)
png(file = "plot1.png", width = 480, height = 480)
hist(data$Global_active_power, col = "red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()